CREATE TABLE USER_ROLES
(
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
ROLE VARCHAR(50) NOT NULL,
USER_ID BIGINT(20)NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT FK_USER_CONSTRAINT FOREIGN KEY(USER_ID) REFERENCES USER_TABLE(ID)
)